version: '3'
services:
  elastic-server:
    build: .
    restart: always
    ports:
      - '5001:5001'
    volumes:
      - .:/app
      - .:/bitnami/elasticsearch/data
    depends_on:
      - elasticsearch
    networks:
      - bkmrkd

  elasticsearch:
    image: bitnami/elasticsearch:7
    container_name: elasticsearch
    ports:
      - '9200:9200'
    environment:
      - ELASTICSEARCH_ADVERTISED_HOSTNAME=elasticsearch
      - ELASTICSEARCH_ADVERTISED_PORT_NUMBER=9200
      - ELASTICSEARCH_ALLOW_REMOTE_CONNECTIONS=yes
    volumes:
      - ./elasticsearch:/bitnami/elasticsearch/data
    networks:
      - bkmrkd

networks:
  bkmrkd:
    driver: bridge
